[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[project]
authors = [
    {name = "Alexander Sidorov",email = "alexander@sidorov.dev"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Telecommunications Industry",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python",
    "Topic :: Communications :: Chat",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
dependencies = [
    "aiohttp[speedups] (>=3.11.18,<4.0.0)",
    "pydantic (>=2.11.3,<3.0.0)",
]
description = "Library for Telegram Bot API"
keywords = ["telegram"]
license = {text = "MIT"}
name = "oyabun"
readme = "README.md"
requires-python = "<3.13.0,>=3.12.0"
version = "2025.4.20"

[project.urls]
repository = "https://github.com/tgrx/oyabun"


[tool.isort]
force_single_line = true
line_length = 79
multi_line_output = 3
no_sections = true
py_version = 312
src_paths = ["src", "tests"]


[tool.mypy]
cache_dir = "/home/developer/caches/mypy"
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
exclude = [
  "__pycache__",
  ".git",
  ".local",
  ".venv",
]
explicit_package_bases = true
packages = ["oyabun", "samurai", "tests"]
no_implicit_optional = true
plugins = [
  "pydantic.mypy",
]
pretty = true
python_version = "3.12"
show_error_context = true
sqlite_cache = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
    "PIL",
]


[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true


[tool.poetry]
exclude = [
    "__pycache__",
    "*.pyc",
    "*.pyd",
    "*.pyo",
    "*~",
    "pyproject.toml",
    "samurai",
]
include = [
    "README.md",
    "LICENSE",
]
package-mode = true
packages = [{include = "oyabun", from = "src"}]


[tool.poetry.group.dev.dependencies]
attrs = "25.3.0"
autoflake = "2.3.1"
devtools = {extras = ["pygments"], version = "0.12.2"}
ipython = "9.1.0"
isort = "6.0.1"
mypy = "1.15.0"
pillow = "11.2.1"
pytest = "8.3.5"
pytest-aiohttp = "1.1.0"
pytest-asyncio = "0.26.0"
pytest-cov = "6.1.1"
ruff = "0.11.6"
tomlkit = "0.13.2"


[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
cache_dir = "/home/developer/caches/pytest/"
console_output_style = "count"
filterwarnings = [
    "ignore::DeprecationWarning",
]
testpaths = [
    "tests",
]
addopts = "--cov --cov-fail-under=50"


[tool.ruff]
cache-dir = "/home/developer/caches/ruff"
exclude = [
  "__pycache__",
  ".git",
  ".local",
  ".venv",
]
include = ["pyproject.toml", "src/**/*.py", "tests/**/*.py"]
indent-width = 4
line-length = 79
target-version = "py312"


[tool.ruff.format]
docstring-code-format = false
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false


[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN",
  "COM812",
  "D",
  "E501",  # TODO(refactoring): uncomment later
  "EM102",  # TODO(refactoring): uncomment later
  "FBT003",  # TODO(refactoring): uncomment later
  "I001",
  "N802",
  "PGH003",  # TODO(refactoring): uncomment later
  "PLR0913",  # TODO(refactoring): uncomment later
  "PLR2004",
  "RET504",
  "S101",
  "SIM117",  # TODO(refactoring): uncomment later
  "TD003",
  "FIX002",
  "TRY003",  # TODO(refactoring): uncomment later
  "TRY300",  # TODO(refactoring): uncomment later
  "TRY301",  # TODO(refactoring): uncomment later
  "N818",  # TODO(refactoring): uncomment later
  "PT018",  # TODO(refactoring): uncomment later
]